### ISSUE TITLE
 ApkInstaller.install(filePath); line giving error

### ISSUE THREAD

**Issue by shahidshafique** [wayne214/react-native-apk-install#1]
ApkInstaller.install(filePath); line giving following error any solution

Attempt to invoke virtual method 'android.content.res.XmlResourceParser android.content.pm.ProviderInfo.loadXmlMetaData(android.content.pm.PackageManager, java.lang.String)' on a null object reference
parsePathStrategy
    FileProvider.java:605
getPathStrategy
    FileProvider.java:579
getUriForFile
    FileProvider.java:417
install
    RNApkInstallModule.java:60
invoke
    Method.java
invoke
    JavaMethodWrapper.java:372
invoke
    JavaModuleWrapper.java:158
run
    NativeRunnable.java
handleCallback
    Handler.java:873
dispatchMessage
    Handler.java:99
dispatchMessage
    MessageQueueThreadHandler.java:29
loop
    Looper.java:193
run
    MessageQueueThreadImpl.java:232
run
    Thread.java:764

**Comment by wayne214** [comment]
ok,it's the permission problem. there is the article can help you.
